//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Biddanondo.Dbs
{
    using System;
    using System.Collections.Generic;
    
    public partial class Collection
    {
        public Collection()
        {
            this.Items = new HashSet<Item>();
        }
    
        public int Id { get; set; }
        public string RestaurantName { get; set; }
        public int PreservationTime { get; set; }
        public string Location { get; set; }
        public Nullable<int> RestaurantId { get; set; }
    
        public virtual ICollection<Item> Items { get; set; }
        public virtual Restaurant Restaurant { get; set; }
    }
}
