//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Biddanondo.Dbs
{
    using System;
    using System.Collections.Generic;
    
    public partial class Restaurant
    {
        public Restaurant()
        {
            this.Collections = new HashSet<Collection>();
        }
    
        public int Id { get; set; }
        public string RestaurantName { get; set; }
        public string Location { get; set; }
        public string Password { get; set; }
    
        public virtual ICollection<Collection> Collections { get; set; }
    }
}
