//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace newVaccineform.DB
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;
    public partial class Registration_Form
    {
        [Required(ErrorMessage = "Please enter your name")]
        [RegularExpression("^[a-zA-Z]+$", ErrorMessage = "provide valid name")]
        [MinLength(3, ErrorMessage = "Name length must be greater than 3")]
        [MaxLength(35, ErrorMessage = "Length must be less than 35")]
        public string Name { get; set; }
        [Required(ErrorMessage = "Please enter your email")]
        [RegularExpression("^[0-9+-_.]+@[a-zA-Z0-9.]+$", ErrorMessage = "must be valid email")]
        public string Email { get; set; }
        [Required(ErrorMessage = "Please enter your Phone number")]
        [RegularExpression("(^(1){1}[3-9]{1}(\\d){8})$", ErrorMessage = "Must be valid phone number")]
        public int Phone_No { get; set; }
        [DateRange(18, ErrorMessage = "You're age must be greater than 18")]
        [DisplayName("Date of Birth")]
        [DataType(DataType.Date), DisplayFormat(DataFormatString = "{0:dd/MM/yyyy}", ApplyFormatInEditMode = true)]
        public System.DateTime Date { get; set; }
        [Required]
        public string Gender { get; set; }
        [Required]
        public string BG { get; set; }
        [DataType(DataType.Password)]
        [Required(ErrorMessage = "Please insert password")]
        [MinLength(8, ErrorMessage = "Password must have 8 characters")]
        public string Password { get; set; }
        [DataType(DataType.Password)]
        [Compare("Password", ErrorMessage = "Password not matching")]
        public string ConfirmPassword { get; set; }
    }
}
